CHAPTER = "4"
AI_DIR = "../ai"
DICTIONARY_DIR = "../dictionary/sources"
DEFAULT_VERB_TYPE = 'う'
DEFAULT_PARTICLE = 'を'
DEFAULT_ADJECTIVE_TYPE = 'い'
DEFAULT_ADJECTIVE_PARTICLE = None
DEFAULT_PREPOSITION_TYPE= 'place'
